### ISSUE TITLE
Кнопки направления

### ISSUE THREAD

**Issue by Des-75** [MuzzYSoft/SoFSWClient-for-Android#16]
Вот точно бесит, когда кнопки север/юг/запад/восток меняют своё местоположение!
Предлагаю таки закрепить их внизу экрана над "обновить/карта/меню".
чтобы было так:
|______на север______|
|_на запад_|_на восток_|
|________на юг_______|
|___тут нижнее меню__|
Отсутствующие направления  - делать неактивными (даже если оно только одно). Если отсутствуют все направления - тогда можно вообще не показывать.

**Comment by MuzzYSoft** [comment]
Спасибо, сделано. Осталась некритичная проблема с урезанием длинных текстов на устройствах с маленьким экраном.

**Comment by Des-75** [comment]
Пока не закрывай. Тестю. Думаю.

**Comment by MuzzYSoft** [comment]
сменил вместо - емоджи значком 🚷
