### ISSUE TITLE
Шкатулки

### ISSUE THREAD

**Issue by Des-75** [MuzzYSoft/SoFSWClient-for-Android#17]
После "Clear history" бота, нажимаю "старт", приходит:
"Здравствуйте! Вы перешли в игру по ссылке данной Вам другом. Вы уже играете в нашу игру, Ваш друг получит шкатулку только по приглашению новых игроков. Пожалуйста, не забудьте его предупредить об этом.
Попробуйте сыграть в нашу игру, для чего нажмите кнопку ниже."
Это норм? Лично я не понял как это сообщение относится ко мне. И, даже если относится, что я должен делать и зачем эти лишние телодвижения? Раз перешёл по ссылке данной другом, то из этой ссылки должно быть понятно, кому вручать шкатулку.

**Comment by MuzzYSoft** [comment]
Спасибо! Исправлено.
