### ISSUE TITLE
Мусор

### ISSUE THREAD

**Issue by Des-75** [MuzzYSoft/SoFSWClient-for-Android#19]
Вылазит при стройке.
![err](https://cloud.githubusercontent.com/assets/19542693/15594920/8863d9ea-23e4-11e6-9099-b0014e11ba69.png)

**Comment by Des-75** [comment]
+ к мусору:
/sel1- арендовать землю (50 дринк в сутки)
/sel4- **4-** освободить незанятые строениями земли

**Comment by Des-75** [comment]
```
Выбрана вещь: 
огненный кристалл (вещь) 
----

----
```

Зачем дефисы, переносы строки?

**Comment by MuzzYSoft** [comment]
Между дефисами должно быть такое, но нужны человеко-часы для их заполнения
Выбрана вещь: 
серое перо (вещь) 
----
Чем выше птица, тем неожиданнее гадит
----

**Comment by Des-75** [comment]
:) ок
