### ISSUE TITLE
Юзерфрендли

### ISSUE THREAD

**Issue by Des-75** [MuzzYSoft/SoFSWClient-for-Android#20]
Напоминаю об идее введения доп. кнопки "инвентарь" на локации "призрачный фонтан", и предлагаю унифицировать ещё сильнее - добавить 3 кнопки "огненный", "призрачный", "морозный".
Можно добавлять/убирать эти кнопки при наличии/отсутствии соответствующих кристаллов, или же проверять только после нажатия соответствующей кнопки.

**Comment by MuzzYSoft** [comment]
добавил кнопку "поискать кристаллы в вещах"
а маленькое неудобство пусть будет, чтоб был стимул строить свой кораблик )

**Comment by Des-75** [comment]
c отдельной кнопкой "вещи" смысл кнопки "поискать..." полностью исчез. Убери, не трать место на экране.
