### ISSUE TITLE
Мусор #2

### ISSUE THREAD

**Issue by Des-75** [MuzzYSoft/SoFSWClient-for-Android#24]
Кнопка "список вещей" после применения огненного кристалла просто занимает место на экране.
Хотя, кмк, именно для вещей необходимо будет сделать постоянную кнопку. Она очень часто используется и запихивать её внутрь интерфейса нелогично. Можно, конечно, юзать "02"... но.. кнопки круче.

**Comment by MuzzYSoft** [comment]
добавил кнопку
